export enum REWARD_TYPES {
  REFERRAL = 'REFERRAL',
  DEPOSIT = 'DEPOSIT',
}

export enum REDEEM_METHOD {
  PER_TRADE = 'PER_TRADE',
}

export enum REWARD_ACTION {
  CREDITED = 'CREDITED',
  DEPOSITED = 'DEPOSITED',
  LAPSED = 'LAPSED',
}
