export const ERROR_CODES: { [key: string]: string } = {

  'auth/admin-restricted-operation': 'Admin only.',
  'auth/app-not-authorized': 'App not authorized.',
  'auth/app-not-installed': 'App not installed.',
  'auth/captcha-check-failed': 'Invalid reCAPTCHA.',
  'auth/code-expired': 'Code Expired.',
  'auth/cordova-not-ready': 'Cordova not ready.',
  'auth/cors-unsupported': 'Unsupported browser.',
  'auth/credential-already-in-use': 'Credential in use.',
  'auth/custom-token-mismatch': 'Invalid custom token.',
  'auth/requires-recent-login': 'Please login again.',
  'auth/dynamic-link-not-activated': 'Activate Dynamic Links.',
  'auth/email-change-needs-verification': 'Verify email for multi-factor users.',
  'auth/email-already-in-use': 'Email in use.',
  'auth/expired-action-code': 'Action Code Expired.',
  'auth/cancelled-popup-request': 'Popup request cancelled.',
  'auth/internal-error': 'Internal error.',
  'auth/invalid-app-credential': 'Invalid app verifier.',
  'auth/invalid-app-id': 'Invalid app ID.',
  'auth/invalid-user-token': 'Invalid user token.',
  'auth/invalid-auth-event': 'Internal error.',
  'auth/invalid-verification-code': 'Invalid OTP',
  'auth/invalid-continue-uri': 'Invalid URL.',
  'auth/invalid-cordova-configuration': 'Missing Cordova plugins.',
  'auth/invalid-custom-token': 'Invalid custom token.',
  'auth/invalid-dynamic-link-domain': 'Invalid dynamic link domain.',
  'auth/invalid-email': 'Invalid email.',
  'auth/invalid-api-key': 'Invalid API key.',
  'auth/invalid-cert-hash': 'Invalid certificate hash.',
  'auth/invalid-credential': 'Invalid credential.',
  'auth/invalid-message-payload': 'Invalid email template.',
  'auth/invalid-multi-factor-session': 'Invalid multi-factor session.',
  'auth/invalid-oauth-provider': 'Unsupported provider.',
  'auth/invalid-oauth-client-id': 'Invalid OAuth client ID.',
  'auth/unauthorized-domain': 'Domain not authorized.',
  'auth/invalid-action-code': 'Invalid action code.',
  'auth/wrong-password': 'Invalid password.',
  'auth/invalid-persistence-type': 'Invalid persistence type.',
  'auth/invalid-phone-number': 'Invalid phone number.',
  'auth/invalid-provider-id': 'Invalid provider ID.',
  'auth/invalid-recipient-email': 'Invalid recipient email.',
  'auth/invalid-sender': 'Invalid sender email.',
  'auth/invalid-verification-id': 'Invalid verification ID.',
  'auth/invalid-tenant-id': 'Invalid tenant ID.',
  'auth/multi-factor-info-not-found': 'No second factor found.',
  'auth/multi-factor-auth-required': 'Second factor required.',
  'auth/missing-android-pkg-name': 'Missing Android Package Name.',
  'auth/auth-domain-config-required': 'Include authDomain in firebase.initializeApp().',
  'auth/missing-app-credential': 'Missing app verifier.',
  'auth/missing-verification-code': 'Missing verification code.',
  'auth/missing-continue-uri': 'Missing URL.',
  'auth/missing-iframe-start': 'Internal error.',
  'auth/missing-ios-bundle-id': 'Missing iOS Bundle ID.',
  'auth/missing-multi-factor-info': 'No second factor identifier.',
  'auth/missing-multi-factor-session': 'Missing proof of first factor.',
  'auth/missing-or-invalid-nonce': 'Invalid or missing nonce.',
  'auth/missing-phone-number': 'Missing recipient phone number.',
  'auth/missing-verification-id': 'Missing verification ID.',
  'auth/app-deleted': 'FirebaseApp deleted.',
  'auth/account-exists-with-different-credential': 'Account exists with different credentials.',
  'auth/network-request-failed': 'Network error.',
  'auth/no-auth-event': 'Internal error.',
  'auth/no-such-provider': 'User not linked to provider.',
  'auth/null-user': 'Null user object.',
  'auth/operation-not-allowed': 'Operation not allowed.',
  'auth/operation-not-supported-in-this-environment': 'Operation not supported.',
  'auth/popup-blocked': 'Popup blocked.',
  'auth/popup-closed-by-user': 'Popup closed.',
  'auth/provider-already-linked': 'User already linked with provider.',
  'auth/quota-exceeded': 'Quota exceeded.',
  'auth/redirect-cancelled-by-user': 'Redirect cancelled by user.',
  'auth/rejected-credential': 'Rejected credentials.',
  'auth/second-factor-already-in-use': 'Second factor already enrolled.',
  'auth/maximum-second-factor-count-exceeded': 'Max second factors exceeded.',
  'auth/tenant-id-mismatch': 'Tenant ID mismatch.',
  'auth/timeout': 'Operation timed out.',
  'auth/user-token-expired': 'User token expired. Sign in again.',
  'auth/too-many-requests': 'Too many requests. Try again later.',
  'auth/unauthorized-continue-uri': 'Unauthorized continue URL.',
  'auth/unsupported-first-factor': 'Unsupported first factor.',
  'auth/unsupported-persistence-type': 'Unsupported persistence type.',
  'auth/unsupported-tenant-operation': 'Unsupported operation in multi-tenant context.',
  'auth/unverified-email': 'Verify email.',
  'auth/user-cancelled': 'User denied permissions.',
  'auth/user-not-found': 'User not found.',
  'auth/user-disabled': 'User account disabled by admin.',
  'auth/user-mismatch': 'Credentials do not match user.',
  'auth/user-signed-out': '',
  'auth/weak-password': 'Weak password.',
  'auth/web-storage-unsupported': 'Unsupported browser or disabled cookies.',
  'auth/session-expired': 'Session expired. Please login again.'
};