export const LIMIT_TRANSACTION_FEE_PERCENTAGE = 1.5;
export const MARKET_TRANSACTION_FEE_PERCENTAGE = 2;

export const orderStatusText = {
  FULFILLED: 'EXECUTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  INIT: 'OPEN',
  OPEN: 'OPEN',
  PARTIAL_FULFILLED: 'OPEN',
  PARTIAL_CANCELLED: 'OPEN',
  DECREMENTED: 'DECREMENTED'
};